name: Trigger auto deployment for paddyapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/paddyapp-AutoDeployTrigger-db0c4085-5406-476e-822c-0301111a5d0e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: paddyacr.azurecr.io
          username: ${{ secrets.PADDYAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.PADDYAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: paddyacr.azurecr.io/paddyapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PADDYAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n paddyapp -g paddygroup --server paddyacr.azurecr.io --username  ${{ secrets.PADDYAPP_REGISTRY_USERNAME }} --password ${{ secrets.PADDYAPP_REGISTRY_PASSWORD }}
            az containerapp update -n paddyapp -g paddygroup --image paddyacr.azurecr.io/paddyapp:${{ github.sha }}
